### ISSUE TITLE
Artifact Caching Proxy - make the first path prefix configurable

### ISSUE THREAD

**Issue by sboardwell** [jenkins-infra/helm-charts#1157]
### What feature do you want to see added?

Currently the artifact-caching-proxy uses some predefined paths to allow falling back to different locations. This is mentioned here:

https://github.com/jenkins-infra/helm-charts/blob/b7a7b0c7f0d95539459170893099f3e81980c941/charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml#L104

However, this only works for the current specific use case of OSS Jenkins Infa. I would like to make the `/public` string below configurable so as to allow caching of artifacts which are not found behind the `/public` prefix.

https://github.com/jenkins-infra/helm-charts/blob/b7a7b0c7f0d95539459170893099f3e81980c941/charts/artifact-caching-proxy/templates/nginx-proxy-configmap.yaml#L110

e.g. 
https://repo.jenkins-ci.org/public/com/byclosure/jenkins/plugins/gcloud-sdk/0.0.3/gcloud-sdk-0.0.3.hpi
vs
https://jenkins-updates.cloudbees.com/download/plugins/gcloud-sdk/0.0.3/gcloud-sdk.hpi

**Comment by dduportal** [comment]
Fixed by https://github.com/jenkins-infra/helm-charts/pull/1169
