### ISSUE TITLE
Replace azureFile volumes by Azure CSI

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#163]
Some charts use [azureFile volumes](https://kubernetes.io/docs/concepts/storage/volumes/#azurefile), without PV/PVC. (see linked closed PR)

Note this type of volume is now deprecated, we have to change these to use Azure CSI.

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/kubernetes-management/issues/2571#issuecomment-1176306039_

**Comment by lemeurherve** [comment]
- don't forget storageClass
- note: the secrets for these charts are stored in sops

**Comment by dduportal** [comment]
Done since [Kubernetes 1.26](https://github.com/jenkins-infra/helpdesk/issues/3683)
