### ISSUE TITLE
Add `nodeSelector` to charts with persistent volumes

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#194]
To avoid https://github.com/jenkins-infra/status/pull/204#issuecomment-1232686477

Can also be done in other ways (taint, etc.)

**Comment by dduportal** [comment]
No need for that: Kubernetes is toplogy aware with PVC (and it even supports zones since some time): https://kubernetes.io/docs/setup/best-practices/multiple-zones/#storage-access-for-zones
