### ISSUE TITLE
Use secrets for `plugin-health-scoring` sensible environment variables

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#327]
https://kubernetes.io/docs/concepts/configuration/secret/#using-secrets-as-environment-variables

https://github.com/jenkins-infra/helm-charts/blob/76dbcaa0ff38a7c5347cb9a78d9cf7ed67858c5f/charts/plugin-health-scoring/templates/deployment.yaml#L59-L62

**Comment by dduportal** [comment]
Closed by #349
