### ISSUE TITLE
[mirrorbits] The rsyncd ingress should be replaced by a load balancer

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#625]
> The ingress should be replaced by a load balancer like it's done for the LDAP service, as rsync is a TCP service, not a HTTP one.

_Originally posted by @lemeurherve in https://github.com/jenkins-infra/kubernetes-management/issues/4278#issuecomment-1690314082_

**Comment by dduportal** [comment]
As I explained in https://github.com/jenkins-infra/helm-charts/pull/627#pullrequestreview-1592901914, I vote for this issue in the kubernetes-management issue tracker rather than helm chart as the default should remain clusterIP

**Comment by hervelemeur** [comment]
As you stated

> Beside, I have a personal preference of setting a kind LoadBalancer by overrding values because it is easier to understand the installatiobn topology (particularly in our case where we specify an annotation for the public IP)

I think this issue can be closed, nothing particular to do here, and no need for a kubernetes one too.
