### ISSUE TITLE
Fix `acme` chart issue: `could not find expected ':'`

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#655]
`helm template acme` output:

> Error: YAML parse error on acme/templates/clusterIssuer.yaml: error converting YAML to JSON: yaml: line 14: could not find expected ':'

Unit tests should be added, doc: https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md

**Comment by linoleparquet** [comment]
Hi, I created a PR to fix this one. Let me know what you think.
