### ISSUE TITLE
Fix `rating` chart issue: `mapping values are not allowed in this context`

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#661]
`helm template rating` output:

> Error: YAML parse error on rating/templates/deployment.yaml: error converting YAML to JSON: yaml: line 37: mapping values are not allowed in this context

Unit tests should be added, doc: https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md

**Comment by dduportal** [comment]
Deployed with success in production in https://github.com/jenkins-infra/kubernetes-management/pull/4545
