### ISSUE TITLE
Fix `reports` chart issue: `could not find expected ':'`

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#662]
`helm template reports` output:

> Error: YAML parse error on reports/templates/deployment.yaml: error converting YAML to JSON: yaml: line 62: could not find expected ':'

Unit tests should be added, doc: https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md

**Comment by linoleparquet** [comment]
Resolved in #772

**Comment by dduportal** [comment]
@linoleparquet for information, issues can be closed automatically if there is a commit message (or in the PR body) with the correct textual form: https://docs.github.com/en/issues/tracking-your-work-with-issues/linking-a-pull-request-to-an-issue#linking-a-pull-request-to-an-issue-using-a-keyword

**Comment by linoleparquet** [comment]
Thanks for the tip !!
