### ISSUE TITLE
Fix `rss2twitter` chart issue: `nil pointer evaluating interface {}.consumerKey`

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#663]
`helm template rss2twitter` output:

> Error: template: rss2twitter/templates/secret.yaml:9:30: executing "rss2twitter/templates/secret.yaml" at <.Values.twitter.consumerKey>: nil pointer evaluating interface {}.consumerKey

Unit tests should be added, doc: https://github.com/helm-unittest/helm-unittest/blob/main/DOCUMENT.md

**Comment by dduportal** [comment]
- Release after #716 was merged
- Deployed to production in https://github.com/jenkins-infra/kubernetes-management/pull/4378

👏
