### ISSUE TITLE
The `helm-unittest` updatecli target should be of type `file` instead of `yaml`

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#709]
The target https://github.com/jenkins-infra/helm-charts/blob/3e42c7017714ed480be2342d06234825f24ac296/updatecli/updatecli.d/helm-unittest.yaml#L25-L32 should be of type `file` to avoid updatecli YAML parser adding a `null` after `workflow_dispatch` while it shouldn't: https://github.com/jenkins-infra/helm-charts/pull/706#discussion_r1327111845

<img width="375" alt="image" src="https://github.com/jenkins-infra/helm-charts/assets/91831478/82d09aba-ed65-4e3a-be30-1ebd628f399a">

**Comment by dduportal** [comment]
Is that a problem?

I see that the workflow_dispatch is still enabled:

<img width="1495" alt="Capture d’écran 2023-09-15 à 20 30 43" src="https://github.com/jenkins-infra/helm-charts/assets/1522731/4d4b93ae-2a91-407f-b1d6-677fa724a82e">

It looks like it is valid. Using `file` means having a regexp which is a PITA to maintain, so better to keep updatecli doing this if it is valid YAML + GHA syntax no?

**Comment by lemeurherve** [comment]
I've removed the `null` manually. For GitHub `workflow_dispatch:` is valid, while the YAML parser wants to add a `null` to it: `workflow_dispatch: null`

**Comment by dduportal** [comment]
- There are no differences in strict YAML between `workflow_dispatch:`, `workflow_dispatch: null` or even ``workflow_dispatch: Null`: that is why the parser is correct, but it's *visually* annoying. Ref. the YAML specification for `null` https://yaml.org/type/null.html

- There are no differences in GHA (functionally speaking) between `workflow_dispatch:`, `workflow_dispatch: null` and `workflow_dispatch: {}`: the 3 syntaxes enable the button to trigger manually a build.  So wether you've removed the `null` value or not , the feature is correct: hence my question "what is the problem you want to solve"

Again, using a file with a pattern is hard to keep (the amount of fixes we've had to fix over time...) compared to a native YAML system. If there are no problem, I don't understand why we should trade the native resource with another?

**Comment by hervelemeur** [comment]
As you said, it's visually annoying, that's all.

As there is only one dependency to keep up to date, the compromise doesn't seem too big for me.

Then I didn't intended to argue that much, feel free to close this issue.
