### ISSUE TITLE
[jenkinsio] The instructions how to run the chart yourself are outdated

### ISSUE THREAD

**Issue by lemeurherve** [jenkins-infra/helm-charts#944]
### Describe your use-case which is not covered by existing documentation.

The instructions at https://github.com/jenkins-infra/helm-charts/tree/main/charts/jenkinsio#running-this-yourself are outdated:
https://github.com/jenkins-infra/helm-charts/blob/74b7e45a6ad2f4cc7715b51896174c0fbcede90e/charts/jenkinsio/README.md#L11-L12

- The jenkins.io job has been moved into another folder of ci.jenkins.io: https://ci.jenkins.io/job/Websites/job/jenkins.io/
- This job doesn't archive the zipped build content, there is currently no artifacts stored for this job since https://github.com/jenkins-infra/jenkins.io/pull/6244

This chart README should be updated with instructions how to build this archive yourself by cloning https://github.com/jenkins-infra/jenkins.io, running `make archive` then grab the zip archive from ./build/archives/

**Comment by lemeurherve** [comment]
cc @kmartens27 who noticed the issue.

**Comment by kmartens27** [comment]
I can confirm that the instructions that @lemeurherve has provided do result in getting the jenkins.io build zip file as described.

**Comment by SarathChandra24** [comment]
This issue has been address in the PR: https://github.com/jenkins-infra/helm-charts/pull/1028, can close this issue.

**Comment by dduportal** [comment]
@kmartens27 @lemeurherve it looks good to close for me, can you confirm as you were the last ones to try these instructions?

**Comment by lemeurherve** [comment]
LGTM, thanks @SarathChandra24!
